name: Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
      message:
        description: "Message"
        required: true

jobs:
  commit:
    runs-on: ubuntu-22.04
    env:
      VERSION: ${{ github.event.inputs.version }}
      MESSAGE: ${{ github.event.inputs.message }}
      BRANCH: "release-${{ github.event.inputs.version }}"
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: Create a new branch
      run: |
        git checkout -b $BRANCH

    - name: Update image tag
      run: /bin/bash ./hack/version.sh $VERSION

    - name: Commit
      run: |
        git add .
        git commit -m "New version from GitHub Actions"
        git push --set-upstream origin $BRANCH

    - name: Tag
      run: |
        git tag $VERSION -m "$MESSAGE"
        git push origin $VERSION

    - name: Create PR
      run: gh pr create -B ${GITHUB_REF#refs/heads/} -H $BRANCH --title "Test PR from Actions" --body "This is a test PR" | gh pr merge --admin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
