name: Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
      message:
        description: "Message"
        required: true

jobs:
  commit:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Test change
      run: |
        date > test.txt
    
    - name: Set git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: Commit
      run: |
        git add test.txt
        git commit -m "New date from GitHub Actions"
        git push origin ${GITHUB_REF#refs/heads/}

  create-tag:
    needs: commit
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create Tag
      uses: negz/create-tag@v1
      with:
        version: ${{ github.event.inputs.version }}
        message: ${{ github.event.inputs.message }}
        token: ${{ secrets.GITHUB_TOKEN }}
